apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: java-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-microservice
    spec:
      containers:
        - name: java-microservice-container
          image: public.ecr.aws/g4d6r5w8/cloud-capstone:latest
          ports:
            - containerPort: 4567