spring:
  jackson:
    default-property-inclusion: NON_NULL

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key:  ${AWS_SECRET_ACCESS_KEY}
    region:
      static: eu-central-1
      auto: false

s3:
  image-bucket: cloud-capstone-images-818222958857
  signed-url-expires-in-seconds: 600

dummy-secret: ${DUMMY_SECRET}